# Generated by Django 5.0 on 2023-12-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_todoitem_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='cor',
            new_name='color',
        ),
    ]
