# Generated by Django 5.0 on 2023-12-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_cor_todoitem_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='postzinho',
        ),
    ]
