# Generated by Django 5.0 on 2023-12-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postzinho_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='postzinho',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
