# Generated by Django 5.0 on 2023-12-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postzinho_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postzinho',
            name='signt',
            field=models.CharField(default='anon', max_length=50),
        ),
    ]
